# Generated by Django 4.2.5 on 2023-09-29 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_time_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterChapterView',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.post')),
            ],
            bases=('news.post', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='FilterPostView',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.category')),
            ],
            bases=('news.category', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.category')),
            ],
            bases=('news.category', django.views.generic.list.ListView),
        ),
    ]
